Lab3
vsalavatov/bsse-2020-scala-tg-bot pull request #1
Opened 2020-03-07 10:09 UTC by jeinygroove

2020-03-11 14:54 UTC, eld0727 requested changes

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/Bot.scala
> +    if (!messagesForUser.contains(toUser))
getOrElseUpdate тут думаю будет проще

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/Bot.scala
> +        Random.shuffle(response.unsafeBody.data.flatMap(_.images)).head.link
headOption + match лучше чем try catch

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/PhotoTrait.scala
> +    request(SendPhoto(msg.source, photo, caption, parseMode, disableNotification, replyToMessageId, replyMarkup))
Если вы хотите скачивать файл и отправлять его прямо как фото, то лучше это сделать через http клиент скачав это изображение асинхронно. Source апи же это будет делать синхронно и заблокирует поток исполнения

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/Bot.scala
> +    backend.send(request).map { response =>
Внутри Future принято не бросать исключения, лучше сделать через flatMap + Future.successful / Future.failed

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/Bot.scala
> +  def getAllUsers() = {
Можно просто one line expression

2020-03-11 14:54 UTC, eld0727 commented on src/main/scala/Bot.scala
> +class Server {
Лучше разнесите разные части по разным файлам

2020-03-12 11:51 UTC, jeinygroove commented on src/main/scala/PhotoTrait.scala
> +    request(SendPhoto(msg.source, photo, caption, parseMode, disableNotification, replyToMessageId, replyMarkup))
мы же по идее сами не скачиваем, а отправляем тг ссылку на файл и он уже сам его скачивает

2020-03-12 12:00 UTC, jeinygroove commented
@eld0727 внесли правки (почему-то кнопка re-request отказывается работать)

2020-03-24 07:08 UTC, eld0727 commented on src/main/scala/Bot.scala
> +class PictureService(val imgurClientId: String)(implicit val backend: SttpBackend[Future, Nothing], implicit val ec: ExecutionContext) {
Сервис и всё что его касается лучше тоже вынести в отдельный файл

2020-03-24 07:18 UTC, eld0727 approved these changes

2020-04-20 07:39 UTC, eld0727 approved these changes

2020-04-23 10:44 UTC, merged