Lab5
vsalavatov/bsse-2020-scala-tg-bot pull request #3
Opened 2020-04-09 20:57 UTC by vsalavatov

2020-04-20 08:21 UTC, eld0727 requested changes

2020-04-20 08:21 UTC, eld0727 commented on src/main/scala/bsse2018/tgbot/ServerDB.scala
> +    Await.result(resultFuture, Duration.Inf)
У вас не должно быть Await нигде, кроме тестов и main

2020-04-23 11:36 UTC, vsalavatov commented
@eld0727 fixed
в 6ую лабу тоже изменения залил

2020-05-06 14:05 UTC, eld0727 approved these changes

2020-05-07 12:32 UTC, merged